version: "3.8"

services:
  browserui:
    build:
      dockerfile: ./Dockerfile
    command: sh -c "yarn install && yarn run start"
    ports:
      - 8080:8080
    working_dir: /browser_ui
    volumes:
      - ./:/browser_ui
